name: push@dev
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: fetch
        run: cd $GITHUB_WORKSPACE && git fetch https://dev.fron.io/s/bqv/r/nixrc
      - name: reset
        run: git reset --hard FETCH_HEAD
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: live
          rebase: true
          name: Github Action
          email: github@fron.io
