name: build@flake-check
on:
  pull_request:
    branches:
     - live
     - actions
  push:
    branches:
     - live
     - actions
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v10
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20200618_377345e/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes ca-references recursive-nix" | sudo tee -a /etc/nix/nix.conf
    # Run the general flake checks
    - run: nix flake check
    # Verify that the shell builds
    - run: nix dev-shell -c echo OK
