name: build@nixosConfigurations.delta
on:
  pull_request:
    branches:
     - live
     - actions
  push:
    branches:
     - live
     - actions
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - run: nix shell -c 'nix build .#nixosConfigurations.delta'
